### ISSUE TITLE
Deprecation warning in Symfony 4.4

### ISSUE THREAD

**Issue by garak** [doctrine/DoctrineBundle#1020]
In latest Symfony (version 4.4.0-DEV), this bundle is causing the following deprecation warning:
>The "Doctrine\Bundle\DoctrineBundle\Registry" class implements "Symfony\Bridge\Doctrine\RegistryInterface" that is deprecated since Symfony 4.4, use Doctrine\Common\Persistence\ManagerRegistry instead.

**Comment by alcaeus** [comment]
This is a deprecation that can't be solved without a BC break. It is already fixed in 2.0, which will support Symfony 5. Thanks for bringing this up.

**Comment by nicolas-grekas** [comment]
We could add an adhoc rule in DebugClassLoader to skip this deprecation if this is reported too often.

**Comment by alcaeus** [comment]
We allow a single deprecation warning in the 4.4 tests to account for this, but if you can exclude this specific error that'd be great!

**Comment by arderyp** [comment]
I agree, if its an unfixable issue, the specific warning should be suppressed (still an issue now in 2021)

**Comment by alcaeus** [comment]
This is not an issue with 2.x, which is the only supported version. There's nothing to fix here.
